
### What is Karma
Karma  is action on three levels: body, mind and energy. Whatever you do on these three levels leaves a certain residue or imprint upon you. Karma is not some external system of crime and punishment. It is an internal cycle generated by you.

### How Karma forms.  
What you consider to be "myself" is just an accumulation of habits, predispositions, and tendencies you have acquired over time without being conscious of the process.  
Your five senses are collecting data from the outside world every moment of your life.  Over time this enormous volume of sense impressions begins to assume a certain distinctive pattern within you. This pattern slowly shapes itself into behavioral tendencies. A cluster of tendencies hardens over time into what you call your personality , or what you claim to be your true nature.

### Karma: Human Learning.  
Depending on the type of physical, mental and energetic actions you perform, you write your software. Once that software is written, your whole system functions accordingly.
As time goes on, you turn into a puppet of your accumulated past.

### Karma: Intention.  
Your intention makes all the differences. If you say something prompted by love, and another person gets hurt, that is his karma not yours. But if you say something out of hatred and another person has no problem with it, it is good karma for them and not for you. The accumulation of karma is determined by your intention, not merely by its impact on someone else. It is the level of bitterness and hatred that causes karma, not the act alone. If you keep repeating the same mental action, it is because you have a personal stake in the matter.You may not be sentenced to prison,but you have imprisoned yourself.


### Karma: Chemical Process.  
Human being is a psychosomatic organism- that whatever happens in the mind  immediately imprints itself on the body as a chemical process. If you think of mountains, for instance, your chemistry will react in one way vs if you think of snakes. You might not be aware of it unless these sensations become acute. All these sensations register and over time become the blueprint of your unconscious mind. You are therefore a living repository of karmic memory on levels you are not aware of.

### Karma: working
Working out karma means that the play of your life simply organizes itself in order to fulfill your inclinations. Karma is not a punishment or reward, it is just the process by which life tries to fulfill itself.
